networks:
  laravel:
    driver: bridge

services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app
    ports:
      - "8000:8000"
    depends_on: 
      mysql:
        condition: service_healthy
      vite:
        condition: service_started
    command:
      - php artisan serve --host=0.0.0.0 --port 8000
    networks:
      - laravel

  queue:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: queue-worker
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app
    depends_on: 
      mysql:
        condition: service_healthy
    command:
      - php artisan queue:work --sleep=3 --tries=1 --timeout=0
    networks:
      - laravel

  vite:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: vite
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app
    ports:
      - "5173:5173"
    command:
      - npm run dev

  mysql:
    platform: linux/amd64
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - laravel
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s

volumes:
  mysql-data:
